name: "baseline"
type: "Dense"
hidden_layer_neurons: 10
output_activation: "sigmoid"
lr:
  low: 0.0001
  high: 0.01
  log: true
batch_size: [16, 32, 64]
dropout:
  use: true
  low: 0.1
  high: 0.5
hidden_layer_activation: "relu"
