name: "baseline"
type: "Dense"
hidden_layer_neurons: 10
output_activation: "sigmoid"
lr:
  low: 0.0001
  high: 0.01
  sampling: "log"
  log: true
batch_size: [16, 32, 64]
hidden_layer_activation: "relu"