name: "model1"
type: "Dense with dropout"
layers: [64, 32]
output_activation: "sigmoid"
lr:
  default: 0.001
  low: 0.0001
  high: 0.01
  sampling: "log"
batch_size: [16, 32]
dropout:
  low: 0.1
  high: 0.5
  step: 0.1
  default: 0.1
activation_options: ["relu", "tanh"]
