experiment_name: "breast_cancer_prediction"
log_models: true
save_artifacts: false
plots: "plots"
comparison_table: "model_comparison.json"
artifacts:
  base_dir: "artifacts"
  model: "model"                          
  preprocessing:                           
    base_dir: "preprocessing"    
    scaler: "scaler.pkl"                   
    encoder: "encoder.pkl"                 
    features: "features.json"             
