channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.1.1
  - keras-tuner==1.4.7
  - numpy==2.2.6
  - pandas==2.3.2
  - scikit-learn==1.7.2
  - scipy==1.15.3
  - tensorflow==2.20.0
name: mlflow-env
