epochs: 4
callbacks: []
optimizer:
  type: "adam"
  lr:
    default: 0.001
    low: 0.0001
    high: 0.01
    sampling: "log"
scheduler:
  type: "cosine"
  warmup_epochs: 5
loss: "binary_crossentropy"
metrics: ['accuracy', 'precision', 'recall']



