defaults:
  - data: data
  - model: baseline # default model
  - training: train
  - evaluation: eval
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

seed: 42
experiment_name: breast_cancer_nn
