defaults:
  - data: data
  - model: baseline # default model
  - training: train
  - tuning: tune
  - evaluation: eval
  - logging: mlflow
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled


seed: 42
experiment_name: breast_cancer_nn
